name: Build Tweak
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y git make curl unzip liblzma-dev

      - name: Install THEOS (official script, 自动拉完整theos，包含子模块)
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          bash -c "$(curl -fsSL https://mirror.ghproxy.com/https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Build package
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make package

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
